### ISSUE TITLE
Bug: 3rd level subdomain nameHash (x.y.z.eth) computes wrong hash.

### ISSUE THREAD

**Issue by dhadrien** [danfinlay/eth-ens-namehash#27]
```
    const getLabelhash = (label: string) =>
     utils.keccak256(utils.toUtf8Bytes(label));


      const subdomain = 'subdomain.sismo.eth';
      const userLabel = 'newUser';
      const userLabelHash = getLabelhash(userLabel);
      const subdomainNode = nameHash.hash(subdomain);
      const userNode = nameHash.hash(`${userLabel}.${subdomain}`);
      const userNode2 = keccak256(
        ethers.utils.solidityPack(
          ['bytes', 'bytes'],
          [subdomainNode, userLabelHash]
        )
      );
      console.log('test-child-node', userNode);
      console.log('test-child-node-2', userNode2);
 ```
 
 Gives back 
 ```
test-child-node 0x379502eb5529d1cc3d6b894572eddd51d2125ac39e2d6ff86f74a149e2be446d
test-child-node-2 0xa751ab40833eca0e8ea09a43258d42d31585278282f8355241eadd1f22f031e7
 ```

The second way to compute the hash is correct while the first one is incorrect.

**Comment by mdtanrikulu** [comment]
It's funny to say but, it's not a bug. It's a feature! 🥳 

The reason you have different hashes, because there is an uppercase letter in your 3rd level subdomain. Which is not forbidden but cursed (invalid). 🧙

[This bit here](https://github.com/danfinlay/eth-ens-namehash/blob/c623e73d8eb48c5370a2116e9c4fa96fb07a85e9/index.js#L26), will normalize your domain name and the domain name will become `newuser.subdomain.sismo.eth` as it stands the namehash will be different. 

If you try with lowercase version of userLabel `const userLabel = 'newuser';` you'll see everything is fine.

**Comment by dhadrien** [comment]
Ah great! I had already seen this and forgot ^^

Thanks - and sorry for this :)
